# Generated by Django 3.2 on 2021-09-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.CharField>'),
        ),
    ]
