# Generated by Django 3.2 on 2021-09-09 08:46

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210908_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.get_artist_upload_path),
        ),
    ]
