# Generated by Django 3.2 on 2021-10-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_album_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='image_url',
        ),
        migrations.AddField(
            model_name='album',
            name='special_offer_category',
            field=models.CharField(choices=[('no_offer', 'No Offer'), ('new_arrival', 'New Arrival'), ('deal', 'Deal'), ('clearance', 'Clearance')], default='no_offer', max_length=254),
        ),
    ]
