# Generated by Django 3.2 on 2021-10-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211006_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
